language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env: SYMFONY_VERSION=3.4.*
    - php: 7.3
      env: SYMFONY_VERSION=4.2.*;ASSETIC=skip
    - php: 7.3
      env: SYMFONY_VERSION=4.3.*;ASSETIC=skip
    - php: 7.0
      env: SYMFONY_VERSION=3.0;COMPOSER_FLAGS="--prefer-dist --prefer-lowest";TWIG_VERSION=^2.4
    - php: 7.0
      env: SYMFONY_VERSION=3.0;COMPOSER_FLAGS="--prefer-dist --prefer-lowest";TWIG_VERSION=^1.34
    - php: 7.3
      env: SYMFONY_VERSION=@dev;ASSETIC=skip
    - php: 7.3
      env: DEPENDENCIES=beta
  allow_failures:
    - php: 7.3
      env: SYMFONY_VERSION=@dev;ASSETIC=skip
    - php: 7.3
      env: DEPENDENCIES=beta

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - if [ "$ASSETIC" != "skip" ]; then composer require "kriswallsmith/assetic:^1.1" --no-update; fi;
  - if [ "$TWIG_VERSION" != "" ]; then composer require twig/twig:$TWIG_VERSION --no-update; fi
  - if [ "$DEPENDENCIES" != "" ]; then composer config minimum-stability $DEPENDENCIES; fi;

install: composer update --prefer-source $COMPOSER_FLAGS

script: ./vendor/bin/phpunit --coverage-text